### ISSUE TITLE
Specified and default compilers in installation script

### ISSUE THREAD

**Issue by tomashalada** [mosaic-group/openfpm_pdata#5]
In case that `./install` is called with specified system variables for compilers  `CXX=/usr/bin/gcc-12` and `CC=/usr/bin/gcc-12` there is notification about this in the script

```
----------------------------------------------------------------------
 Selected compilers
----------------------------------------------------------------------
 The user request to use specifics compilers to compile C/C++ or Fortran code
 specifing one or more of these variables CXX/CC/F77/FC. When at least one is
 defined the specified compiler will be used.
 When not specified the system will use the default g++/gcc/gfortran/gfortran
 The installer will use the following compilers

CXX=/usr/bin/gcc-12
CC=/usr/bin/gcc-12
F77=gfortran
FC=gfortran
gfortran  SUCCESS
OpenMPI is CUDA aware
```

however, during the installation procedure, `CXX` is not reflected
```
-- The C compiler identification is GNU 12.3.0
-- The CXX compiler identification is GNU 13.2.1
```
or in case of the dependencies
```
-- Detected Compiler: GCC 13.2.1.
```

I needed to export `OMPI_CXX` to compile with desired version of `g++`, so the output of the install script is a bit confusing.

**Comment by syaskovets** [comment]
Thank you for reporting the issue. Now we got rid of the `install` script in the version 5.0 the issue should be gone. Please let me know if it persists.

**Comment by tomashalada** [comment]
Resolved with the new install procedure.
