### ISSUE TITLE
Issues with SPH examples.

### ISSUE THREAD

**Issue by tomashalada** [mosaic-group/openfpm_pdata#9]
- Examples `7_SPH_dlb_gpu_opt` and `7_SPH_dlb_gpu_more_opt` contain function `vector_dist.merge` that does not exist. This functions is used only for sensors (which are commented out) and it seems that sensors work also without this function.

- The smoothing function `Wab` is wrong in interval 1 < r/h < 2 and produces negative values.

I will fix both soon.

**Comment by syaskovets** [comment]
Thank you for the fixes provided. Closing the issue as fixed
